services:
  pluralkit-relay:
    build: /mnt/cache/docker-compose/PluralKit-Relay
    container_name: pluralkit-relay
    ports:
      - "3000:3000"
    environment:
      API_KEY: "YOUR_API_KEY_HERE"
      SYSTEM_ID: "YOUR_SYSTEM_ID_HERE"